version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/challenge
      - RABBITMQ_URI=amqp://rabbitmq:5672
    volumes:
      - ./uploads:/app/uploads

  worker:
    build: .
    container_name: worker
    command: ["/app/wait-for-rabbit.sh", "rabbitmq", "yarn", "start:worker"]
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/challenge
      - RABBITMQ_URI=amqp://rabbitmq:5672
    volumes:
      - ./uploads:/app/uploads
